### ISSUE TITLE
Build gdal 1.11.3 for OSX

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#629]
Due to the log limit of 4MB I am building `gdal 1.11.3`one by one.  (This `gdal` will be used to build `fiona` and `rasterio`.)

(See https://github.com/travis-ci/travis-ci/issues/5014)

- [X] PY 27 and NPY 19  (#656)
- [X] PY 27 and NPY 110 (#657)
- [X] PY 34 and NPY 19 (#658)
- [X] PY 34 and NPY 110 (#659)
- [X] PY 35 and NPY 19 (#660)
- [X] PY 35 and NPY 110  (#661)

**Comment by ocefpaf** [comment]
See https://github.com/travis-ci/travis-ci/issues/5014

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA It turns out that the OSX-Travi-CI "failure" was only the log size.  I build one by one and now we have `gdal 1.11.3` for OSX on the channel :tada:

**Comment by ChrisBarker-NOAA** [comment]
On Thu, Dec 17, 2015 at 3:01 AM, Filipe <notifications@github.com> wrote:

> @ChrisBarker-NOAA <https://github.com/ChrisBarker-NOAA> It turns out that
> the OSX-Travi-CI "failure" was only the log size. I build one by one and
> now we have gdal 1.11.3 for OSX on the channel
>
awesome!

-CHB





> —
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ioos/conda-recipes/issues/629#issuecomment-165423101>.
>



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov
